### ISSUE TITLE
Runnning npm test giving this error can you please help with this.

### ISSUE THREAD

**Issue by vinay0981123** [mike-lischke/java2typescript#11]
[
![image](https://github.com/mike-lischke/java2typescript/assets/85073024/87acef3f-ccbe-4e66-b1ad-05b740b9b588)

![image](https://github.com/mike-lischke/java2typescript/assets/85073024/260f5a91-f31c-418f-9014-0aee4bf32303)
](url)

**Comment by mike-lischke** [comment]
I assume you have installed the node modules properly. What Node.js version is on your box? For me the tests run fine, both from VS Code and from a terminal.
