### ISSUE TITLE
Generation of inconsistent import statements

### ISSUE THREAD

**Issue by JuergenMutschall** [mike-lischke/java2typescript#2]
```
example:
package com.metamodules.helloworld;

import java.lang.System;

class HelloWorld {
    public static void main(String args[]) {
        System.out.println("Hello World!");
    }
}
```

generates

```
import { java } from "../../../../lib/java";


export class HelloWorld {
    public static main(args: string[]): void {
        java.lang.System.out.println("Hello World!");
    }
}
```
but needs 
`import { java } from "../../../../lib/java/java";`

Please provide a directory layout for generated typescript libs and applications.

**Comment by JuergenMutschall** [comment]
Workaround: Issue can be fixed by providing a deeper "link" in  library options of the converter configuration:
`javaLib: "/home/juergen/work/java2typescript/lib/java/java",`

**Comment by mike-lischke** [comment]
OK, looks like you figured out a solution. I guess I can move the java.ts file in lib/java one level up to avoid having to import `lib/java/java`. But that's just a cosmetic issue.
