### ISSUE TITLE
How to migrate a GWT project?

### ISSUE THREAD

**Issue by x2nie** [mike-lischke/java2typescript#24]
Hi Mr. Mike,

I need your advice.
I am migrating a project that uses GWT (com.google.gwt). that is actually will running in browser, so the code are a lot of DOM (web-browser) objects involved;  that is what GWT supposed to be.

My later migrated code (typescript fles) wouldn't need to be compatible with java any more. I mean will be purely in typescript for running in FireFox/Chrome.  I am sure with this path, because I've downloaded the running html page somewhere, and play with them locally (without java webserver) and that is worked as identical as the online version.  I mean the generated JS by compiling GWT is standalone, no need to fetching data from the webserver.

Okay. My plan was to migrate java file one by one, because I need to modify GWT's object/property line by line.
Well, I think that is worse, since there are huge files needed to be inspected.

So, in case you know a better approach, that would be great to know. ?

here is the repo I am migrating with: https://github.com/x2nie/circuitts2-migration-java2ts/tree/master/src/com/lushprojects/circuitjs1/client
and here is the option I am using so far:
```json
    "sourceReplace": {
        "(native)": "/*-na-ti-ve-*/"
    },
    "targetReplace": {
        "java\\.lang\\.Enum": "Enum",
        "java\\.lang\\.String": "string",
        "\\/\\*-\\{": "{",
        "\\}-\\*\\/": "}"
    },
    "options": {
        "addNullUnionType": false
    }
```

**Comment by mike-lischke** [comment]
In such cases I either first translate the 3rd party lib (using java2ts) or, if that's too large, manually create a symbol table with the APIs needed by the main code. This is what I did for [Java](https://github.com/mike-lischke/java2typescript/blob/master/src/JavaPackageSource.ts) where I load the symbol table data from JSON files I extracted from the official documentation. With that you can mostly keep the original API calls, but have to come up with an own implementation.

But keep in mind UI related stuff is the most difficult code to translate, as that very often contains platform specific code.

**Comment by x2nie** [comment]
oh? reasonable idea. I can follow that way.
Thanks you !
